version: '3'
services:
  app:
    build: .
    container_name: autosurf-backend
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./captcha-data:/usr/src/app/captcha-data
    environment:
      - NODE_ENV=development
    security_opt: 
      - seccomp=unconfined
    cap_add:
      - SYS_ADMIN
    networks:
      - app-network

networks:
  app-network:
    driver: bridge