version: '3'
services:
  app:
    build: .
    container_name: autosurf-backend
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./captcha-data:/usr/src/app/captcha-data
    environment:
      - NODE_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge